### ISSUE TITLE
Question: switch plate needed?

### ISSUE THREAD

**Issue by sohocoke** [LouWii/ErgoMax#11]
Hi, I love this layout and am planning to order parts and give it a shot. I'm considering it a prototyping effort to find zero-in on the right switch and layout, so am planning to do a minimal build without a case.

One question: do the MX switches stay secure enough in the socket for daily use without a switch plate securing them? The Gerber file doesn't have an FR4 switch plate so hoping this is the case.

**Comment by jaspreetlall** [comment]
No, not stable at all.
I am in the process of building this board as well.
Tried installing switches without the plate (I don't have it made yet) and I'd say that it won't be usable in any real life scenario. The pins on the switches are delicate and the middle stem is just minimal support.

All that being said, this is the first time I am ever building a keyboard so I am using all the parts for the first time. I am willing to share some pictures if you need.

**Comment by LouWii** [comment]
@jaspreetlall are you using 3 pins or 5 pins switches?

I've tested out with 5 pins Gateron blacks and they fit quite snug on the PCB, I think it would be fine to use them like that. 3 pins switches are too loose for sure.

@sohocoke You could try to use one of the CAD files to make a plate. Layer 3 is the one that would be the plate. I'm not sure if having just a plate without the entire case would help that much, but I've never tried.

**Comment by sohocoke** [comment]
@jaspreetlall @LouWii Thanks for your help. I ordered Kailh Speed Coppers which I've just found are 3-pin switches. 😟 

I'll have a look at the CAD files and see if I could make a plate, but since this is my first build attempt I guess even if I pull it off, it might take me quite some time.

**Comment by LouWii** [comment]
Yeah the reversible PCB doesn't support 5 pins switches. I don't remember why I made it that way :/

**Comment by BenMMcLean** [comment]
@LouWii 

I am working on a 5-pin revision. Haven't made a PR yet since the routing is pretty bad and I haven't validated it yet, but if you want you can see it in the main branch of my fork -> https://github.com/BenMMcLean/ErgoMax

**Comment by sohocoke** [comment]
`CAD/Acryllic/left - layer 3 - plate.pdf` seems to have some content truncated. 

I found a way to convert the .dwg file to a .dxf file that I could open in LibreCAD. There are a few layers in this file. The layer for the switch plate seems to be 'Orig switch cut' – could you confirm? 

My plan is to get quotes from a local acrylic laser cutting service and order if the price is reasonable.

**Comment by LouWii** [comment]
@sohocoke I've updated the repo and cleaned up the files for the case. Have a look there: https://github.com/LouWii/ErgoMax/tree/master/Case/Acrylic/MakersLabs These are the files I used to build the case for my ErgoMax. Layer 3 is indeed the plate.

**Comment by sohocoke** [comment]
I just finished building the reversible version and found out that with the Kailh hot swap sockets and Kailh Speed Silver switches, the switches are relatively secure and don't wobble in normal use at my desk. So no switch plate is necessary, although it would definitely make things more stable if you plan to move the keyboard around a lot.
