### ISSUE TITLE
VIA Support

### ISSUE THREAD

**Issue by leifniem** [LouWii/ErgoMax#4]
While i found a mention of the right half supporting VIA, the software3 doesn't seem to recognize either half of the keyboard.

Are there any steps required except for adding the via_right.json?

Also it seems kbfirmwarebuilder reach EOL, which might make VIA or a keymap.json for QMK configurator a good addition to the repo.

Thank you in advance :)

**Comment by LouWii** [comment]
When I tried to make the board show up in VIA, I was not able to get it to work. I actually created an issue in their repo at the time https://github.com/the-via/releases/issues/18. A few people tried giving some solution there, but I never got around testing them out. I'm not using my ErgoMax, so I can't really try anything for now.

**Comment by leifniem** [comment]
Thanks, if i ever find time to take a stab at this i'll let you know how it goes :)

**Comment by LouWii** [comment]
Thanks! 😄
