### ISSUE TITLE
[question] Does the PCB work with Kailh Low Profile Choc Switches?

### ISSUE THREAD

**Issue by alain-sarti** [LouWii/ErgoMax#5]
Hi there,

I am new to the whole mechanical keyboard topic so maybe this question is a bit stupid, but I wanted to ask if the PCB is compatible with Kailh Low Profile Choc Switches? I want to use those and find the extra F-keys on this layout intriguing. 

Thanks in advance

**Comment by LouWii** [comment]
I actually don't know. You will have to check if they have the same footprint as regular Cherry MX switches. What I'm sure though is that the case I designed will not work with those switches.

**Comment by alain-sarti** [comment]
Thanks for the information, I'll check and if it does I'll let you know ☺️

**Comment by madushan1000** [comment]
@alain-sarti did you ever find out if they're compatible?

**Comment by alain-sarti** [comment]
I don't know for sure, but mx and choc are not compatible according to this webpage: https://learn.adafruit.com/neokey-breakout/overview
