### ISSUE TITLE
Ground plane is disconnected on reversible PCB

### ISSUE THREAD

**Issue by BenMMcLean** [LouWii/ErgoMax#9]
First off, great project! This board is exactly what I was looking for.

On the reversible PCB, the ground plane is not connected to the microcontroller. This condition allows each half to operate individually but they cannot operate together over a TRRS cable, as the microcontrollers will not share a ground. This could be fixed by adding a ground plane on both sides of the PCB.

Having assembled the board, everything else appears to function correctly (although it would be nice to have a 5 pin switch footprint).

**Comment by LouWii** [comment]
Thanks for the feedback @BenMMcLean. Could you post some pictures? I'm curious about how it looks, I've never built the reversible PCB version.

I actually don't know why I haven't used the 5 pins switch footprint. I need to motivate myself to change that and fix the ground plane.

**Comment by BenMMcLean** [comment]
Yeah sure! I haven't got a photo of the wire I spliced between the Microcontroller & TRRS jack, but I've attached a picture of the completed board & the bare PCB.

![image](https://user-images.githubusercontent.com/6789217/219584599-01ce01d3-9323-4cdb-8747-a141ad80af7a.png)
![image](https://user-images.githubusercontent.com/6789217/219584673-a327e7f7-4973-40e6-a9aa-f8193c92993b.png)
![image](https://user-images.githubusercontent.com/6789217/219584717-692ea60b-f631-4d23-a186-73e515a6921d.png)

I had to make some modifications to the acrylic case in order to fit my microcontroller and the TRRS jack, but it otherwise fit pretty well.

**Comment by LouWii** [comment]
Nice, it looks pretty good with a white case. Do you mind if I add the pictures somewhere in one of the doc?

**Comment by BenMMcLean** [comment]
Go ahead!

**Comment by MLouttit** [comment]
Thanks for the heads up @BenMMcLean! I ordered PCBs before the change, so I'll get a photo of the wire if I remember. Out of interest, what keycap set is that?

**Comment by BenMMcLean** [comment]
@MLouttit It's a combination of a few sets actually. I found it cheaper to buy a specific "ergodox" set rather than parting out individual 1.5 and 2u keys, so I got the green keycaps from [here](https://www.aliexpress.com/item/1005004040895139.html?spm=a2g0o.order_list.order_list_main.325.58cb1802QDpweG). The pink caps I had left over from a different build, bought from here [here](https://www.aliexpress.com/item/1005004021955113.html?spm=a2g0o.order_list.order_list_main.320.58cb1802QDpweG). The rest of the keys are just a generic set for a standard keyboard, I paid about AUD$20 for them.

**Comment by BenMMcLean** [comment]
> Hi, I am waiting for my reversible PCBs to arrive. Is this issue rectifiable after the board has been printed?

If you downloaded the gerbers after February 17, you have a revised version of the board without this issue. If your gerbers are from a date prior, the fix is extremely simple. All you need to do is splice a wire between the ground on the TRRS jack and the ProMicro. I've highlighted the two pins you need to connect in the diagram below (make sure you've got the board the same way up I do):
<img width="1012" alt="Screenshot 2023-05-06 at 12 08 20 pm" src="https://user-images.githubusercontent.com/6789217/236593109-cd437674-00bc-4c14-8e3d-2ee2314727ba.png">
